# Generated by Django 5.1.3 on 2025-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=15)),
                ('disease_desc', models.TextField()),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='eyeImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('eye_side', models.CharField(choices=[(1, 'left'), (2, 'right')], max_length=6)),
                ('image_date', models.DateField(blank=True, null=True)),
                ('image_type', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('image_result', models.CharField(max_length=15)),
                ('image_desc', models.TextField()),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_upload',
            },
        ),
    ]
