# Generated by Django 5.1.3 on 2025-01-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='eyeImage',
        ),
    ]
