# Generated by Django 5.1.3 on 2025-01-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_delete_disease_delete_eyeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=15)),
                ('disease_desc', models.TextField()),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='eyeImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('eye_side', models.CharField(choices=[(1, 'left'), (2, 'right')], max_length=6)),
                ('image_date', models.DateField(blank=True, null=True)),
                ('image_type', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('image_result', models.CharField(max_length=15)),
                ('image_desc', models.TextField()),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
