# Generated by Django 5.1.3 on 2025-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_disease_eyeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AlterField(
            model_name='eyeimage',
            name='image_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
