# Generated by Django 5.1.3 on 2025-01-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_delete_imageupload_alter_eyeimage_image_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyeimage',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
