# Generated by Django 5.1.3 on 2025-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_alter_eyeimage_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePatientRelation',
            fields=[
                ('image_patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_id', models.IntegerField(db_column='image_id')),
                ('patient_id', models.IntegerField(db_column='patient_id')),
            ],
            options={
                'verbose_name': 'Image-Patient Relation',
                'verbose_name_plural': 'Image-Patient Relations',
                'db_table': 'image_patient',
            },
        ),
    ]
