# Generated by Django 5.1.3 on 2025-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_imagepatientrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDiseaseRelation',
            fields=[
                ('image_disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_id', models.IntegerField(db_column='image_id')),
                ('disease_id', models.IntegerField(db_column='disease_id')),
            ],
            options={
                'verbose_name': 'Image-Disease Relation',
                'verbose_name_plural': 'Image-Disease Relations',
                'db_table': 'image_disease',
            },
        ),
    ]
