# Generated by Django 5.1.3 on 2025-01-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_delete_imagediseaserelation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='eyeImage',
        ),
    ]
