# Generated by Django 5.1.3 on 2025-01-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_patient_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
