# Generated by Django 5.1.3 on 2025-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('birthday', models.DateField()),
                ('record', models.TextField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
