# Generated by Django 5.1.3 on 2025-01-20 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('doctor_patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to='user.patient')),
            ],
            options={
                'verbose_name': 'Doctor-Patient Relation',
                'verbose_name_plural': 'Doctor-Patient Relations',
                'db_table': 'doctor_patient',
            },
        ),
    ]
