# Generated by Django 5.1.3 on 2025-01-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_doctor_managers_remove_doctor_date_joined_and_more'),
        ('user', '0005_doctorpatientrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpatientrelation',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrelation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='doctor_id',
            field=models.ForeignKey(db_column='doctor_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to='Login.doctor'),
            preserve_default=False,
        ),
    ]
