# Generated by Django 5.1.3 on 2025-01-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_patient_doctorpatientrelation_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientrelation',
            name='doctor_id',
        ),
    ]
