# Generated by Django 5.1.3 on 2025-01-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_doctor'),
        ('user', '0007_remove_doctorpatientrelation_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='doctor_id',
            field=models.ForeignKey(db_column='doctor_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to='Login.doctor'),
            preserve_default=False,
        ),
    ]
