# Generated by Django 5.1.3 on 2025-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_doctorpatientrelation_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='doctor_id',
            field=models.IntegerField(db_column='doctor_id'),
        ),
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='patient_id',
            field=models.IntegerField(db_column='patient_id'),
        ),
    ]
