# Generated by Django 5.1.3 on 2025-01-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctorpatientrelation_doctor_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientRelation',
        ),
    ]
