# Generated by Django 5.1.3 on 2025-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_doctorpatientrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('doctor_patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField(db_column='doctor_id')),
                ('patient_id', models.IntegerField(db_column='patient_id')),
            ],
            options={
                'verbose_name': 'Doctor-Patient Relation',
                'verbose_name_plural': 'Doctor-Patient Relations',
                'db_table': 'doctor_patient',
            },
        ),
    ]
