# Generated by Django 5.1.3 on 2025-01-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_doctorpatientrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientRelation',
        ),
    ]
