# Generated by Django 5.1.3 on 2025-01-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_doctorpatientrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientRelation',
        ),
    ]
