# Generated by Django 5.1.3 on 2025-01-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_doctor_managers_remove_doctor_date_joined_and_more'),
        ('user', '0007_remove_doctorpatientrelation_doctor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
