# Generated by Django 5.1.3 on 2025-01-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_doctor'),
        ('user', '0008_doctorpatientrelation_doctor_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='doctor1',
        ),
    ]
