# Generated by Django 5.1.3 on 2025-01-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_rename_doctor_doctor1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor1',
            new_name='doctor',
        ),
    ]
