# Generated by Django 5.1.3 on 2025-01-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_rename_doctor1_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
