# Generated by Django 5.1.3 on 2025-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkInfo',
            fields=[
                ('check_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('position', models.CharField(choices=[(1, 'chief_physician'), (2, 'associate_physician'), (3, 'attending_doctor')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('result', models.IntegerField(default=0)),
                ('advice', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'check_info',
            },
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminName',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctorName',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
