# Generated by Django 5.1.3 on 2025-03-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_checkinfo_rename_adminname_admin_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinfo',
            name='alter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='is_password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='position',
            field=models.CharField(choices=[('chief_physician', '主任医师'), ('associate_physician', '副主任医师'), ('attending_doctor', '主治医师')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(choices=[('chief_physician', '主任医师'), ('associate_physician', '副主任医师'), ('attending_doctor', '主治医师')], default='attending_doctor', max_length=20),
        ),
    ]
