# Generated by Django 5.1.3 on 2025-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_checkinfo_alter_time_checkinfo_check_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinfo',
            name='alter_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
