# Generated by Django 5.1.3 on 2025-03-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_checkinfo_alter_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkInfo',
        ),
    ]
