# Generated by Django 5.1.3 on 2025-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_delete_checkinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkInfo',
            fields=[
                ('check_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('position', models.CharField(choices=[('chief_physician', '主任医师'), ('associate_physician', '副主任医师'), ('attending_doctor', '主治医师')], max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('is_password', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('advice', models.CharField(max_length=128, null=True)),
                ('alter_time', models.DateTimeField(blank=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'check_info',
            },
        ),
    ]
