# Generated by Django 5.1.3 on 2025-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_checkinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinfo',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
